# Generated by Django 3.2.7 on 2021-09-28 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48)),
                ("symbol", models.CharField(max_length=4)),
                ("code", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "verbose_name": "currency",
                "verbose_name_plural": "currencies",
                "db_table": "currency",
            },
        ),
        migrations.CreateModel(
            name="DSR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=256)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("failed", "FAILED"), ("ingested", "INGESTED")],
                        default="failed",
                        max_length=48,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsrs",
                        to="dsrs.currency",
                    ),
                ),
            ],
            options={
                "db_table": "dsr",
            },
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48)),
                ("code_2", models.CharField(max_length=2, unique=True)),
                ("code_3", models.CharField(max_length=3)),
                (
                    "local_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territories",
                        to="dsrs.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "territory",
                "verbose_name_plural": "territories",
                "db_table": "territory",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dsp_id", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=255)),
                ("artists", models.CharField(max_length=255)),
                ("isrc", models.CharField(max_length=12)),
                ("usages", models.IntegerField()),
                ("revenue", models.DecimalField(decimal_places=20, max_digits=40)),
                (
                    "dsr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="dsrs.dsr",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dsr",
            name="territory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dsrs",
                to="dsrs.territory",
            ),
        ),
        migrations.AddIndex(
            model_name="currency",
            index=models.Index(fields=["code"], name="currency_code_3257a0_idx"),
        ),
        migrations.AddIndex(
            model_name="territory",
            index=models.Index(fields=["code_2"], name="territory_code_2_c28a9b_idx"),
        ),
    ]
